language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install: "pip install Lektor"

jobs:
  include:
    - stage: build
      script: "lektor build"
    - stage: deploy
      script: "lektor deploy alpha"
